# Generated by Django 2.2.7 on 2020-01-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_to',
            new_name='address_to_name',
        ),
    ]
