# Generated by Django 2.2.7 on 2020-01-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
